

name: StorySpoiler CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
    - uses: actions/checkout@v4
    
    - name: Set up .NET SDK
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore the packages
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
